'use strict';
const BASE='https://hqzsmfeckjoxhoktpdyy.supabase.co';
const KEY='sb_publishable_NPBxELB7s_5Mt4pB-aBflw_UgL80P-b';
const STORE='traitors_session_v22';
const $=id=>document.getElementById(id);
let session=null,state=null,scope='lobby',privateId=null,timer=null,cover=false;
let mediaRecorder=null,mediaStream=null,mediaChunks=[],mediaStartedAt=0,mediaStopTimer=null,voiceBusy=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function authMsg(t,ok=false){$('authMsg').className=ok?'ok':'error';$('authMsg').textContent=t||'';}
function gameErr(t=''){$('gameError').textContent=t;$('gameError').classList.toggle('hidden',!t);}
function setTab(a){$('loginTab').classList.toggle('on',!a);$('activateTab').classList.toggle('on',a);$('loginForm').classList.toggle('hidden',a);$('activateForm').classList.toggle('hidden',!a);authMsg('');}
function saveSession(s){session=s;localStorage.setItem(STORE,JSON.stringify(s));}
function loadSession(){try{session=JSON.parse(localStorage.getItem(STORE)||'null')}catch{session=null}return session;}
function clearSession(){session=null;localStorage.removeItem(STORE);}
async function parse(r){const txt=await r.text();let d=null;try{d=txt?JSON.parse(txt):null}catch{d=txt}if(!r.ok){const e=new Error((d&&d.error_description)||(d&&d.msg)||(d&&d.message)||(d&&d.error)||('HTTP '+r.status));e.status=r.status;throw e}return d;}
async function edge(name,body){return parse(await fetch(BASE+'/functions/v1/'+name,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify(body||{})}));}
async function signIn(email,password){const d=await parse(await fetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({email,password})}));saveSession({access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Date.now()+Math.max(60,(d.expires_in||3600)-30)*1000,user:d.user});return d;}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Session expired');const d=await parse(await fetch(BASE+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY},body:JSON.stringify({refresh_token:session.refresh_token})}));saveSession({access_token:d.access_token,refresh_token:d.refresh_token||session.refresh_token,expires_at:Date.now()+Math.max(60,(d.expires_in||3600)-30)*1000,user:d.user});}
async function ensureToken(){if(!session)loadSession();if(!session?.access_token)throw new Error('Not signed in');if((session.expires_at||0)<Date.now()+5000)await refreshSession();return session.access_token;}
async function rpc(name,args={}){const call=async token=>fetch(BASE+'/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+token},body:JSON.stringify(args||{})});let token=await ensureToken();let r=await call(token);if(r.status===401){await refreshSession();r=await call(session.access_token)}return parse(r);}
async function edgeAuth(name,body){const token=await ensureToken();return parse(await fetch(BASE+'/functions/v1/'+name,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+token},body:JSON.stringify(body||{})}));}
async function logout(){clearInterval(timer);try{if(session?.access_token)await fetch(BASE+'/auth/v1/logout',{method:'POST',headers:{'apikey':KEY,'Authorization':'Bearer '+session.access_token}})}catch{}clearSession();location.reload();}
async function checkConnection(){const box=$('connectionStatus');try{const r=await fetch(BASE+'/functions/v1/resolve-login',{method:'OPTIONS'});if(!r.ok)throw new Error();box.classList.add('online');box.querySelector('span:last-child').textContent='Secure server online'}catch{box.classList.remove('online');box.querySelector('span:last-child').textContent='Cannot reach secure server'}}
$('loginTab').onclick=()=>setTab(false);$('activateTab').onclick=()=>setTab(true);$('logoutBtn').onclick=logout;$('elimLogout').onclick=logout;
$('activateBtn').onclick=async()=>{const sid=$('actStudent').value.trim(),roll=$('actRoll').value.trim(),pw=$('actPassword').value,cf=$('actConfirm').value;if(!sid||!roll)return authMsg('Enter Student ID and Roll Number.');if(pw.length<8)return authMsg('Password must be at least 8 characters.');if(pw!==cf)return authMsg('Passwords do not match.');try{$('activateBtn').disabled=true;authMsg('Creating secure account…',true);const d=await edge('activate-student',{student_id:sid,roll_number:roll,password:pw});await signIn(d.login_email,pw);await boot()}catch(e){authMsg(e.message||'Activation failed.')}finally{$('activateBtn').disabled=false}};
$('loginBtn').onclick=async()=>{const sid=$('loginStudent').value.trim(),pw=$('loginPassword').value;if(!sid||!pw)return authMsg('Enter Student ID and password.');try{$('loginBtn').disabled=true;authMsg('Signing in…',true);const d=await edge('resolve-login',{student_id:sid});await signIn(d.login_email,pw);await boot()}catch(e){authMsg((e.status===400||e.status===401)?'Incorrect password.':'Login failed. If this is your first time, use FIRST ACTIVATION.')}finally{$('loginBtn').disabled=false}};
function roleVisual(){const t=state?.role==='traitor';$('rolePill').textContent=t&&!cover?'TRAITOR':'INNOCENT';$('rolePill').style.color=t&&!cover?'#ff7082':'#71a9ff';$('rolePill').style.borderColor=t&&!cover?'#7b2232':'#224f87';$('traitorBar').classList.toggle('hidden',!(t&&!cover&&state.traitor_room_open));}
$('rolePill').ondblclick=()=>{if(state?.role==='traitor'){cover=!cover;roleVisual()}};
async function boot(){loadSession();if(!session?.access_token){$('authView').classList.remove('hidden');return}try{state=await rpc('get_my_state');if(state.status==='control_account')throw new Error('This account belongs in the Admin panel.');$('authView').classList.add('hidden');if(state.status==='eliminated'||state.status==='blocked'){$('gameView').classList.add('hidden');$('eliminatedView').classList.remove('hidden');$('identityRevealBtn').classList.toggle('hidden',!state.reveal_requested);return}if(state.status!=='active')throw new Error('Player is not active in the current game.');$('eliminatedView').classList.add('hidden');$('gameView').classList.remove('hidden');$('myName').textContent=state.player_name||'PLAYER';$('myClass').textContent=state.class_name||'';$('shieldPill').textContent='🛡 '+(state.shields||0);roleVisual();setChatMode('lobby','MAIN LOBBY');await refreshAll();clearInterval(timer);timer=setInterval(refreshAll,5000)}catch(e){authMsg('Game access error: '+(e.message||e));$('authView').classList.remove('hidden');$('gameView').classList.add('hidden');if(e.status===401)clearSession()}}
async function refreshAll(){try{state=await rpc('get_my_state');if(state.status!=='active')return boot();await rpc('student_presence_heartbeat');const p=await rpc('student_list_lobby_players');const oc=$('onlineCount');if(oc)oc.textContent=(p||[]).filter(x=>x.online).length;roleVisual();await loadMessages();gameErr('')}catch(e){gameErr('Connection issue: '+(e.message||e))}}
async function loadMessages(){const rows=await rpc('student_get_messages_v2',{p_scope:scope,p_private_lobby_id:privateId});$('messages').innerHTML=(rows||[]).map(m=>{const content=m.attachment_type==='voice'?`<button class="voicePlay" data-mid="${m.message_id}">▶ ${esc(m.body||'Voice note')}</button>`:`<div class="body">${esc(m.body)}</div>`;return `<div class="msg"><div class="avatar">${esc(m.sender_initials||'?')}</div><div class="bubble"><div class="meta"><span class="name">${esc(m.sender_label)}</span><span class="time">${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div>${content}<div class="receipt">✓✓ Viewed by ${m.view_count||0}</div></div></div>`}).join('');document.querySelectorAll('.voicePlay').forEach(b=>b.onclick=()=>playVoice(b.dataset.mid,b));const unread=(rows||[]).filter(x=>!x.read_by_me).map(x=>x.message_id);if(unread.length)await rpc('student_mark_messages_read',{p_message_ids:unread});}
async function send(){const t=$('messageInput').value.trim();if(!t)return;$('messageInput').value='';try{await rpc('student_send_message',{p_scope:scope,p_private_lobby_id:privateId,p_body:t});await loadMessages()}catch(e){gameErr(e.message||String(e))}}
$('sendBtn').onclick=send;$('messageInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}};
function setChatMode(newScope,label,lobbyId=null){scope=newScope;privateId=lobbyId;$('chatModeLabel').textContent=label;$('onlineWrap').classList.toggle('hidden',newScope!=='lobby');$('mainLobbyBtn').classList.toggle('hidden',newScope==='lobby');$('roomManageBtn').classList.add('hidden');$('roomManageBtn').onclick=null;gameErr('');}
async function goMainLobby(){setChatMode('lobby','MAIN LOBBY');await loadMessages()}$('mainLobbyBtn').onclick=goMainLobby;
function supportedVoiceMime(){if(!window.MediaRecorder)return'';for(const t of ['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm','audio/ogg;codecs=opus','audio/ogg']){try{if(MediaRecorder.isTypeSupported(t))return t}catch{}}return'';}
function blobToBase64(blob){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result).split(',')[1]||'');fr.onerror=()=>reject(fr.error||new Error('Could not read recording'));fr.readAsDataURL(blob)})}
function resetVoiceUi(){clearTimeout(mediaStopTimer);mediaStopTimer=null;$('voiceBtn').textContent='🎙';$('voiceBtn').classList.remove('recording');$('voiceBtn').disabled=false;$('recordingNote').classList.add('hidden')}
async function startVoice(){if(voiceBusy)return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){gameErr('Voice recording is not supported in this browser. Use current Chrome/Edge or Safari.');return}try{voiceBusy=true;mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=supportedVoiceMime();mediaChunks=[];mediaStartedAt=Date.now();mediaRecorder=mime?new MediaRecorder(mediaStream,{mimeType:mime}):new MediaRecorder(mediaStream);mediaRecorder.ondataavailable=e=>{if(e.data&&e.data.size)mediaChunks.push(e.data)};mediaRecorder.onerror=()=>{gameErr('Voice recording failed.');voiceBusy=false;mediaStream?.getTracks().forEach(t=>t.stop());resetVoiceUi()};mediaRecorder.onstop=async()=>{const duration=Math.min(60000,Date.now()-mediaStartedAt);const actualMime=(mediaRecorder.mimeType||mime||'audio/webm').split(';')[0];mediaStream?.getTracks().forEach(t=>t.stop());mediaStream=null;try{const blob=new Blob(mediaChunks,{type:actualMime});if(!blob.size)throw new Error('No audio was recorded.');if(blob.size>1900000)throw new Error('Voice note is too large. Keep it under 45 seconds.');$('voiceBtn').disabled=true;$('voiceBtn').textContent='…';$('recordingNote').textContent='UPLOADING VOICE NOTE…';const data=await blobToBase64(blob);await edgeAuth('student-media',{action:'upload',scope,private_lobby_id:privateId,mime:actualMime,duration_ms:duration,data_base64:data});await loadMessages();gameErr('')}catch(e){gameErr(e.message||String(e))}finally{voiceBusy=false;$('recordingNote').textContent='● RECORDING VOICE NOTE — tap STOP when finished';resetVoiceUi()}};mediaRecorder.start(250);$('voiceBtn').textContent='■';$('voiceBtn').classList.add('recording');$('recordingNote').classList.remove('hidden');mediaStopTimer=setTimeout(()=>{if(mediaRecorder?.state==='recording')mediaRecorder.stop()},45000)}catch(e){voiceBusy=false;mediaStream?.getTracks().forEach(t=>t.stop());resetVoiceUi();gameErr(e?.name==='NotAllowedError'?'Microphone permission was denied. Allow microphone access and try again.':(e.message||'Could not start microphone.'))}}
$('voiceBtn').onclick=()=>{if(mediaRecorder?.state==='recording')mediaRecorder.stop();else startVoice()};
async function playVoice(messageId,button){try{button.disabled=true;button.textContent='LOADING…';const d=await edgeAuth('student-media',{action:'url',message_id:messageId});const audio=new Audio(d.signed_url);button.classList.add('playing');button.textContent='⏸ PLAYING';audio.onended=()=>{button.classList.remove('playing');button.textContent='▶ VOICE NOTE';button.disabled=false};audio.onerror=()=>{button.classList.remove('playing');button.textContent='▶ VOICE NOTE';button.disabled=false;gameErr('Could not play this voice note.')};await audio.play()}catch(e){button.classList.remove('playing');button.textContent='▶ VOICE NOTE';button.disabled=false;gameErr(e.message||String(e))}}
function show(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;$('sheet').classList.remove('hidden')}function hide(){$('sheet').classList.add('hidden')}$('closeSheet').onclick=hide;
$('playersBtn').onclick=async()=>{try{const p=await rpc('student_list_lobby_players');show('PLAYERS',(p||[]).map(x=>`<div class="listrow"><div class="avatar">${esc(x.initials)}</div><div class="grow"><b>${esc(x.player_name)}</b><small><span class="${x.online?'online':'offline'}">●</span> ${x.online?'Online':'Last seen '+x.last_seen_text} • 🛡 ${x.shields}${x.status==='eliminated'?' • ❌ ELIMINATED':''}</small></div></div>`).join(''))}catch(e){show('ERROR','<div class="error">'+esc(e.message)+'</div>')}};
$('privateBtn').onclick=privatePanel;
async function privatePanel(){try{const rooms=await rpc('student_list_private_lobbies');let h='<div class="card"><b>CREATE PRIVATE LOBBY</b><input id="newRoom" placeholder="Lobby name"><button id="createRoomBtn">CREATE & GET KEY</button></div><div class="card"><b>JOIN WITH KEY</b><input id="joinKey" placeholder="Invite key"><button id="joinRoomBtn">JOIN</button></div>';h+=(rooms||[]).map(r=>`<div class="listrow"><div class="grow"><b>${esc(r.title)}</b><small>Key: ${esc(r.invite_key)}${r.is_owner?' • OWNER':''}</small></div><button class="small roomOpen" data-id="${r.lobby_id}" data-title="${encodeURIComponent(r.title)}">OPEN</button></div>`).join('');show('PRIVATE LOBBIES',h);$('createRoomBtn').onclick=async()=>{try{const d=await rpc('student_create_private_lobby',{p_title:$('newRoom').value});alert('Invite key: '+d.invite_key);await privatePanel()}catch(e){alert(e.message)}};$('joinRoomBtn').onclick=async()=>{try{await rpc('student_join_private_lobby',{p_invite_key:$('joinKey').value.trim()});await privatePanel()}catch(e){alert(e.message)}};document.querySelectorAll('.roomOpen').forEach(b=>b.onclick=()=>openRoom(b.dataset.id,decodeURIComponent(b.dataset.title)))}catch(e){show('ERROR','<div class="error">'+esc(e.message)+'</div>')}}
async function openRoom(id,title){setChatMode('private','PRIVATE // '+title,id);hide();await loadMessages();try{const members=await rpc('student_list_private_members',{p_lobby_id:id});const mine=(members||[]).find(x=>x.user_id===session?.user?.id);if(mine?.is_owner){$('roomManageBtn').classList.remove('hidden');$('roomManageBtn').onclick=()=>manageRoom(id)}}catch{}}
async function manageRoom(id){try{const members=await rpc('student_list_private_members',{p_lobby_id:id});show('LOBBY MEMBERS',(members||[]).map(m=>`<div class="listrow"><div class="grow"><b>${esc(m.player_name)}</b><small>${m.is_owner?'OWNER':'MEMBER'}</small></div>${m.is_owner?'':`<button class="red small kick" data-uid="${m.user_id}">REMOVE</button>`}</div>`).join(''));document.querySelectorAll('.kick').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this member?'))return;try{await rpc('student_kick_private_member',{p_lobby_id:id,p_member_user_id:b.dataset.uid});await manageRoom(id)}catch(e){alert(e.message)}})}catch(e){alert(e.message)}}
$('missionsBtn').onclick=()=>show('MISSIONS','<div class="card"><b>MISSION CONTROL</b><p class="hint">Admin/Game Master launched missions will appear here.</p></div>');
$('voteBtn').onclick=openVote;
async function openVote(){try{state=await rpc('get_my_state');if(!state.vote_open)return show('VOTING','<p class="hint">No voting round is open right now.</p>');const locked=await rpc('student_get_locked_vote');let h='<div class="vote"><div class="voteTitle">'+(state.vote_mode==='murder'?'MURDER // VOTE':'CIRCLE // DOUBT')+'</div><p class="hint" style="text-align:center">Once locked, your vote cannot be changed.</p>';if(!locked.locked){const targets=await rpc('student_list_vote_targets');h+=(targets||[]).map(t=>`<div class="card listrow"><div class="avatar">${esc(t.initials)}</div><div class="grow"><b>${esc(t.player_name)}</b></div><button class="red small lockVote" data-id="${t.member_id}">LOCK</button></div>`).join('')}else{h+=`<div class="card" style="text-align:center"><b>YOUR VOTE IS LOCKED</b><h2 style="color:#ff4962">${esc(locked.target_name)}</h2>${locked.revealed?'<div class="ok">Vote revealed.</div>':locked.called_to_reveal?'<button id="revealVoteBtn" class="primary red">REVEAL MY VOTE</button>':'<div class="hint">Waiting for Game Master to call your reveal.</div>'}</div>`}const tally=await rpc('student_vote_tally');if(tally.reveal_started)h+='<h3>LIVE REVEALED VOTES</h3>'+(tally.rows||[]).map(r=>`<div class="listrow"><div class="grow">${esc(r.player_name)}</div><div class="count">${r.votes}</div></div>`).join('')+`<div class="hint">${tally.revealed_count} of ${tally.total_locked} locked votes revealed.</div>`;h+='</div>';show('VOTE PROTOCOL',h);document.querySelectorAll('.lockVote').forEach(b=>b.onclick=async()=>{if(!confirm('Lock this vote? It cannot be changed.'))return;try{await rpc('student_lock_vote',{p_target_member_id:b.dataset.id});await openVote()}catch(e){alert(e.message)}});if($('revealVoteBtn'))$('revealVoteBtn').onclick=async()=>{try{await rpc('student_reveal_vote');await openVote()}catch(e){alert(e.message)}}}catch(e){show('VOTING','<div class="error">'+esc(e.message)+'</div>')}}
$('blackRoomBtn').onclick=async()=>{if(!(state?.role==='traitor'&&state.traitor_room_open))return;setChatMode('traitor','BLACK ROOM // ANONYMOUS');try{await loadMessages()}catch(e){gameErr(e.message)}};
$('identityRevealBtn').onclick=async()=>{try{const d=await rpc('student_reveal_identity');$('identityResult').innerHTML='<h2 class="'+(d.role==='traitor'?'error':'ok')+'">YOU WERE '+esc(String(d.role).toUpperCase())+'</h2>';$('identityRevealBtn').classList.add('hidden')}catch(e){alert(e.message)}};
window.addEventListener('online',checkConnection);window.addEventListener('offline',checkConnection);checkConnection();loadSession();boot();